services:
  database:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: 2511
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
